name: Build MacOS App
on:
  workflow_call:
    outputs:
      macos_dmg_path:
        value: ${{ jobs.build.outputs.dmg_path }}
      macos_file_dmg_path:
        value: ${{ jobs.build.outputs.file_dmg_path }}

jobs:
  # Build job
  build:
    name: Build MacOS App with Kotlin/Native
    runs-on: macos-latest
    outputs:
      dmg_path: ${{ steps.get_dmg_path.outputs.dmg_path }}
      file_dmg_path: ${{ steps.get_dmg_path.outputs.file_dmg_path }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create environment file
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          cat <<EOF > env.properties
            GEMINI_KEY=$GEMINI_KEY
            BASE_URL=$BASE_URL
          EOF

      - name: Run Package DMG task
        run: ./gradlew packageDmg

      - name: Get the path to the DMG file
        id: get_dmg_path
        run: |
          echo "file_dmg_path=$(find composeApp/build/compose/binaries/main/dmg -name '*.dmg')" >> "$GITHUB_OUTPUT"
          echo "dmg_path=composeApp/build/compose/binaries/main/dmg" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: ${{ steps.get_dmg_path.outputs.file_dmg_path }}
          retention-days: 1
