name: Build Web App
on:
  workflow_call:

jobs:
  # Build job
  build:
    name: Build Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create environment file
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          cat <<EOF > env.properties
            GEMINI_KEY=$GEMINI_KEY
            BASE_URL=$BASE_URL
          EOF

      - name: Run Gradle Tasks
        run: ./gradlew wasmJsBrowserDistribution

      - name: Fix permissions
        run: |
          chmod -v -R +rX "composeApp/build/dist/wasmJs/productionExecutable/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable/