name: Publish Release
on:
  push:
    paths-ignore:
      - 'backend/**'
    branches:
      - main

jobs:
  #  build_web_app:
  #    uses: ./.github/workflows/build_web_app.yaml

  build_macos_app:
    uses: ./.github/workflows/build_macos_app.yaml

  publish_release:
    needs:
      #      - build_web_app
      - build_macos_app
    runs-on: ubuntu-latest
    steps:
      - env:
          MACOS_DMG_PATH: ${{ needs.build_macos_app.outputs.macos_dmg_path }}
        run: echo "$MACOS_DMG_PATH"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release to github
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.MACOS_DMG_PATH }}
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

#  deploy:
#    # Add a dependency to the build job
#    needs: build_web_app
#
#    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
#    permissions:
#      pages: write      # to deploy to Pages
#      id-token: write   # to verify the deployment originates from an appropriate source
#
#    # Deploy to the github-pages environment
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    # Specify runner + deployment step
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4