name: Publish Release
on:
  push:
    paths-ignore:
      - 'backend/**'
    branches:
      - main

jobs:
  build_web_app:
    uses: ./.github/workflows/build_web_app.yaml

  build_macos_app:
    uses: ./.github/workflows/build_macos_app.yaml

  publish_release:
    needs:
      - build_web_app
      - build_macos_app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - env:
          GITHUB_PAGES_URL: ${{ steps.build_web_app.outputs.github_pages_url }}
          MACOS_DMG_PATH: ${{ needs.build_macos_app.outputs.macos_dmg_path }}
          MACOS_DMG_FILE: ${{ needs.build_macos_app.outputs.macos_file_dmg_path }}
        run: echo "$MACOS_DMG_PATH"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read version to release
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: version
          default: 0.0.1
      - name: Download artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: macos-dmg
      - name: Create and release a new GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.download-artifact.outputs.download-path }}
          tag_name: ${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          generate_release_notes: true

  deploy:
    # Add a dependency to the build job
    needs: build_web_app

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ env.GITHUB_PAGES_URL }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4